const translations = {
    ru: {
        monobank: "Монобанк",
        privatbank: "Приватбанк",
        abank: "А-Банк",
        binance: "Binance",
        paymentMethods: "Выберите способ оплаты",
        monobankCardNumber: "Номер карты:",
        monobankRecipient: "Имя получателя:",
        privatbankCardNumber: "Номер карты:",
        privatbankRecipient: "Имя получателя:",
        abankAccountNumber: "Номер счета:",
        abankRecipient: "Имя получателя:",
        binanceWallet: "Кошелек:",
        binanceRecipient: "Имя получателя:",
        copySuccess: "Скопировано в буфер обмена!",
        copyError: "Ошибка при копировании!",
        languageSelected: "Выбран язык: ",
        copyButton: "Копировать",
        themeToggleToDark: "Тёмная тема",
        themeToggleToLight: "Светлая тема"
    },
    ua: {
        monobank: "Монобанк",
        privatbank: "Приватбанк",
        abank: "А-Банк",
        binance: "Binance",
        paymentMethods: "Оберіть спосіб оплати",
        monobankCardNumber: "Номер карти:",
        monobankRecipient: "Ім'я отримувача:",
        privatbankCardNumber: "Номер карти:",
        privatbankRecipient: "Ім'я отримувача:",
        abankAccountNumber: "Номер рахунку:",
        abankRecipient: "Ім'я отримувача:",
        binanceWallet: "Гаманець:",
        binanceRecipient: "Ім'я отримувача:",
        copySuccess: "Скопійовано в буфер обміну!",
        copyError: "Помилка при копіюванні!",
        languageSelected: "Обрано мову: ",
        copyButton: "Копіювати",
        themeToggleToDark: "Темна тема",
        themeToggleToLight: "Світла тема"
    },
    en: {
        monobank: "Monobank",
        privatbank: "PrivatBank",
        abank: "A-Bank",
        binance: "Binance",
        paymentMethods: "Choose a payment method",
        monobankCardNumber: "Card number:",
        monobankRecipient: "Recipient name:",
        privatbankCardNumber: "Card number:",
        privatbankRecipient: "Recipient name:",
        abankAccountNumber: "Account number:",
        abankRecipient: "Recipient name:",
        binanceWallet: "Wallet:",
        binanceRecipient: "Recipient name:",
        copySuccess: "Copied to clipboard!",
        copyError: "Error copying!",
        languageSelected: "Selected language: ",
        copyButton: "Copy",
        themeToggleToDark: "Dark theme",
        themeToggleToLight: "Light theme"
    }
};
