const translations = {
    ru: {
        showQRCodeButton: "Показать QR-код",
        monobank: "Монобанк",
        privatbank: "Приватбанк",
        abank: "А-Банк",
        binance: "Binance",
        paymentMethods: "Выберите способ оплаты",
        monobankCardNumber: "Номер карты:",
        monobankRecipient: "Имя получателя:",
        privatbankCardNumber: "Номер карты:",
        privatbankRecipient: "Имя получателя:",
        abankAccountNumber: "Номер карты:",
        abankRecipient: "Имя получателя:",
        binanceWallet: "Кошелек:",
        binanceRecipient: "ID:",
        copySuccess: "Скопировано в буфер обмена!",
        copyError: "Ошибка при копировании!",
        languageSelected: "Выбран язык: ",
        copyButton: "Копировать",
        openButton: "Открыть",
        themeToggleToDark: "Тёмная тема",
        themeToggleToLight: "Светлая тема",
        bankIconsClickable: "Иконки банков кликабельные, хорошего вам настроения ^^",
        contact: "Контакты",          
        phoneLabel: "Мобильный:",     
        telegramLabel: "Telegram:",   
        phoneLink: "Позвонить",       
        telegramLink: "Открыть",
        recipientName: "Роман Р." // Добавлено имя
    },
    ua: {
        showQRCodeButton: "Показати QR-код",
        monobank: "Монобанк",
        privatbank: "Приватбанк",
        abank: "А-Банк",
        binance: "Binance",
        paymentMethods: "Оберіть спосіб оплати",
        monobankCardNumber: "Номер карти:",
        monobankRecipient: "Ім'я отримувача:",
        privatbankCardNumber: "Номер карти:",
        privatbankRecipient: "Ім'я отримувача:",
        abankAccountNumber: "Номер карти:",
        abankRecipient: "Ім'я отримувача:",
        binanceWallet: "Гаманець:",
        binanceRecipient: "ID:",
        copySuccess: "Скопійовано в буфер обміну!",
        copyError: "Помилка при копіюванні!",
        languageSelected: "Обрано мову: ",
        copyButton: "Копіювати",
        openButton: "Відкрити",
        themeToggleToDark: "Темна тема",
        themeToggleToLight: "Світла тема",
        bankIconsClickable: "Іконки банків клікабельні, гарного вам настрою ^^",
        contact: "Контакти",          
        phoneLabel: "Мобільний:",     
        telegramLabel: "Telegram:",   
        phoneLink: "Подзвонити",      
        telegramLink: "Відкрити",
        recipientName: "Роман Р." // Добавлено имя
    },
    en: {
        showQRCodeButton: "Show QR Code",
        monobank: "Monobank",
        privatbank: "PrivatBank",
        abank: "A-Bank",
        binance: "Binance",
        paymentMethods: "Choose a payment method",
        monobankCardNumber: "Card number:",
        monobankRecipient: "Recipient name:",
        privatbankCardNumber: "Card number:",
        privatbankRecipient: "Recipient name:",
        abankAccountNumber: "Card number:",
        abankRecipient: "Recipient name:",
        binanceWallet: "Wallet:",
        binanceRecipient: "ID:",
        copySuccess: "Copied to clipboard!",
        copyError: "Error copying!",
        languageSelected: "Selected language: ",
        copyButton: "Copy",
        openButton: "Open",
        contact: "Contacts",         
        phoneLabel: "Mobile:",        
        telegramLabel: "Telegram:",    
        phoneLink: "Call",            
        telegramLink: "Open",         
        themeToggleToDark: "Dark theme",
        themeToggleToLight: "Light theme",
        bankIconsClickable: "Bank icons are clickable, have a great day ^^",
        recipientName: "Roman R." // Добавлено имя
    }
};
